### ISSUE TITLE
There is no such package as cortecx in internet

### ISSUE THREAD

**Issue by Khyati-Microcrispr** [Lleyton-Ariton/molecule-generation#1]
pip install cortecx
ERROR: Could not find a version that satisfies the requirement cortecx (from versions: none)
ERROR: No matching distribution found for cortecx

Please search the package on Python Package Index (PyPI)](https://pypi.org/).
I could not able to find such package
Thank you, Khyati

**Comment by Lleyton-Ariton** [comment]
You are correct, the package was yanked a while back.

The 'cortecx' package was used for a padding function. As a quick fix, I have included the padding function from the library into the main code base; requirements.txt have also been updated.

Everything should be working now.
